server:
  port: 10010
spring:
  application:
    name: cloud-eureka
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:10010/eureka