server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
      #remote db aliyun数据库
      # driver-class-name: com.mysql.cj.jdbc.Driver
      # url: jdbc:mysql://ts-yuanh.mysql.rds.aliyuncs.com:3306/cloud?serverTimezone=GMT%2B8&autoR&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      # username: dean
      # password: HYH13554h
      #local db
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql:///cloud?serverTimezone=GMT%2B8&autoR&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: hz13554
      type: com.alibaba.druid.pool.DruidDataSource
  redis:  #未设置密码
    host: 192.168.230.129
  rabbitmq:
    host: 192.168.230.129
    port: 5672
    username: admin
    password: 123456
    virtual-host: /cloud
    #publisher-confirms: true  默认
    publisher-returns: true
    template:
        retry:
          enabled: true
          initial-interval: 10000ms
          max-interval: 80000ms
          multiplier: 2


#myBatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #输出sql日志
  mapper-locations: classpath*:mapper/**Mapper.xml     #.xml目录
  type-aliases-package: com.dean.user.mapper          #接口包
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10010/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
logging:
  level:
    com.dean: info
cloud:
  encoder:
    crypt:
      secret: ${random.uuid} # 随机的密钥，使用uuid
      strength: 10 # 加密强度4~31，决定了密码和盐加密时的运算次数，超过10以后加密耗时会显著增加